                   ---- 30                   
             ---- =             
                   ---- a                   
       ---- expr       

 ---- if block 

       ---- then       
                               ---- 5                               
                         ---- -                         
                   ---- :=                   
                         ---- a                         
             ---- inner block             
       ---- else       

                         ---- 5                         
                   ---- :=                   
                         ---- a                         
             ---- inner block             
program main


