       ---- empty block       
 ---- readln 


                   ---- 0                   
             ---- <             
                   ---- n                   
       ---- expr       

 ---- while block 

       ---- do       
                               ---- 0                               
                         ---- <>                         
                               ---- a                               
                   ---- expr                   

             ---- while block             

                   ---- do                   
                                     ---- n                                     
                               ---- call                               
                                     ---- readln                                     
                         ---- inner block                         
                                           ---- 1                                           
                                     ---- +                                     
                                                 ---- n                                                 
                                           ---- +                                           
                                                 ---- a                                                 
                               ---- :=                               
                                     ---- a                                     
program read_


