       ---- empty block       
 ---- readln 


                   ---- 0                   
             ---- <             
                   ---- n                   
       ---- expr       

 ---- while block 

       ---- do       
                         ---- n                         
                   ---- call                   
                         ---- readln                         
             ---- inner block             
                                     ---- 0                                     
                               ---- >                               
                                     ---- n                                     
                         ---- expr                         

                   ---- if block                   

                         ---- then                         
                                                 ---- 0                                                 
                                           ---- <>                                           
                                                 ---- a                                                 
                                     ---- expr                                     

                               ---- while block                               

                                     ---- do                                     
                                                 ---- a                                                 
                                           ---- call                                           
                                                 ---- readln                                                 
program read_


