             ---- n             
       ---- final expr       

       ---- initial expr       
             ---- 0             

       ---- var i       

 ---- for block 

       ---- to do       
                               ---- i                               
                         ---- *                         
                               ---- 2                               
                   ---- :=                   
                               ---- i                               
                         ---- []                         
                               ---- a                               
             ---- inner block             
                                     ---- 0                                     
                               ---- =                               
                                           ---- 2                                           
                                     ---- mod                                     
                                           ---- i                                           
                         ---- expr                         

                   ---- if block                   

                         ---- then                         
                                           ---- i                                           
                                     ---- *                                     
                                           ---- 2                                           
                               ---- :=                               
                                           ---- i                                           
                                     ---- []                                     
                                           ---- b                                           
                         ---- else                         

                                     ---- i                                     
                               ---- :=                               
                                           ---- i                                           
                                     ---- []                                     
                                           ---- b                                           
program main


