  Type                  Line   Text                            Value                           

  Identificator         1      f                               f                               

  Integer number        5      4                               4                               

  Separator             7      ;                               ;                               

  Identificator         8      k                               k                               

