  Type                  Line   Text                            Value                           

  Integer number        1      0                               0                               

  Integer number        2      01                              1                               

  Integer number        3      123                             123                             

  Integer number        4      0001                            1                               

  Integer number        5      0032                            32                              

  Integer number        5      32                              32                              

  Integer number        5      01010                           1010                            

