  Type                  Line   Text                            Value                           

  Operator              1      -                               -                               

  Real number           1      0.432                           0.432                           

  Operator              2      -                               -                               

  Real number           2      0.432e3                         432                             

  Operator              3      -                               -                               

  Real number           3      432.05e-4                       0.043205                        

