  Type                  Line   Text                            Value                           

  Operator              1      -                               -                               

  Operator              2      +                               +                               

  Operator              3      *                               *                               

  Operator              4      /                               /                               

  Integer number        5      5                               5                               

  Operator              5      div                             div                             

  Integer number        5      2                               2                               

