  Type                  Line   Text                            Value                           

  Operator              1      and                             and                             

  Operator              2      or                              or                              

  Operator              3      xor                             xor                             

  Operator              4      not                             not                             

