  Type                  Line   Text                            Value                           

  Keyword               1      var                             var                             

  Identificator         2      a                               a                               

  Separator             2      :                               :                               

  Identificator         2      integer                         integer                         

  Separator             2      ;                               ;                               

  Keyword               3      begin                           begin                           

  Identificator         4      a                               a                               

  Operator              4      :=                              :=                              

  Integer number        4      20                              20                              

  Operator              4      +                               +                               

  Integer number        4      123                             123                             

  Operator              4      /                               /                               

  Real number           4      3.123e-2                        0.03123                         

  Separator             4      ;                               ;                               

  Keyword               5      end                             end                             

  Separator             5      .                               .                               

