  Type                  Line   Text                            Value                           

  Identificator         1      b                               b                               

  Operator              1      *=                              *=                              

  Integer number        1      43                              43                              

  Operator              1      mod                             mod                             

  Integer number        1      15                              15                              

  Operator              1      +                               +                               

  Integer number        1      43                              43                              

  Identificator         1      div17                           div17                           

