  Type                  Line   Text                            Value                           

  Identificator         1      bool                            bool                            

  Operator              1      :=                              :=                              

  Keyword               1      false                           false                           

  Operator              1      or                              or                              

  Identificator         1      isgood_lexxer                   isgood_lexxer                   

  Keyword               2      if                              if                              

  Identificator         2      isgood_lexxer                   isgood_lexxer                   

  Operator              2      and                             and                             

  Identificator         2      isgood_program_code             isgood_program_code             

  Operator              2      or                              or                              

  Operator              2      not                             not                             

  Identificator         2      isbad_mood                      isbad_mood                      

  Keyword               2      then                            then                            

  Identificator         3      mark_marks                      mark_marks                      

  Operator              3      :=                              :=                              

  Integer number        3      10                              10                              

  Operator              3      -                               -                               

  Identificator         3      day_of_the_day                  day_of_the_day                  

  Operator              3      *                               *                               

  Integer number        3      0                               0                               

