  Type                  Line   Text                            Value                           

  Keyword               1      type                            type                            

  Identificator         2      tpoint                          tpoint                          

  Operator              2      =                               =                               

  Keyword               2      record                          record                          

  Identificator         3      x                               x                               

  Separator             3      ,                               ,                               

  Identificator         3      y                               y                               

  Separator             3      :                               :                               

  Identificator         3      integer                         integer                         

  Separator             3      ;                               ;                               

  Keyword               4      end                             end                             

  Separator             4      ;                               ;                               

  Keyword               5      const                           const                           

  Identificator         6      the_end                         the_end                         

  Operator              6      =                               =                               

  Keyword               6      false                           false                           

  Separator             6      ;                               ;                               

  Keyword               14     end                             end                             

  Separator             14     ;                               ;                               

