  Type                  Line   Text                            Value                           

  Keyword               1      type                            type                            

  Identificator         2      tpoint                          tpoint                          

  Operator              2      =                               =                               

  Keyword               2      record                          record                          

  Identificator         3      x                               x                               

  Separator             3      ,                               ,                               

  Identificator         3      y                               y                               

  Separator             3      :                               :                               

  Identificator         3      integer                         integer                         

  Separator             3      ;                               ;                               

  Keyword               4      end                             end                             

  Separator             4      ;                               ;                               

  Keyword               6      const                           const                           

  Identificator         7      the_end                         the_end                         

  Operator              7      =                               =                               

  Keyword               7      false                           false                           

  Separator             7      ;                               ;                               

  Keyword               8      var                             var                             

  Identificator         9      a                               a                               

  Separator             9      :                               :                               

  Identificator         9      integer                         integer                         

  Separator             9      ;                               ;                               

  Identificator         10     label                           label                           

  Identificator         10     loh                             loh                             

  Separator             10     :                               :                               

  Keyword               12     function                        function                        

  Identificator         12     isemptystr                      isemptystr                      

  Separator             12     (                               (                               

  Identificator         12     a                               a                               

  Separator             12     :                               :                               

  Keyword               12     string                          string                          

  Separator             12     )                               )                               

  Separator             12     ;                               ;                               

  Keyword               13     begin                           begin                           

  Keyword               14     exit                            exit                            

  Separator             14     ;                               ;                               

  Identificator         15     result                          result                          

  Operator              15     :=                              :=                              

  Identificator         15     a                               a                               

  Operator              15     =                               =                               

  Character string      15     ''                                                              

  Separator             15     ;                               ;                               

  Keyword               16     goto                            goto                            

  Identificator         16     loh                             loh                             

  Separator             16     ;                               ;                               

  Keyword               17     end                             end                             

  Separator             17     ;                               ;                               

