  Type                  Line   Text                            Value                           

  Operator              1      /                               /                               

  Operator              1      /                               /                               

  Identificator         1      abcd                            abcd                            

  Separator             3      (                               (                               

  Separator             3      )                               )                               

  Separator             3      )                               )                               

