  Type                  Line   Text                            Value                           

  Keyword               1      program                         program                         

  Identificator         1      programmers_day                 programmers_day                 

  Separator             1      ;                               ;                               

  Keyword               2      var                             var                             

  Identificator         3      isgoodday                       isgoodday                       

  Separator             3      :                               :                               

  Identificator         3      boolean                         boolean                         

  Separator             3      ;                               ;                               

  Keyword               4      begin                           begin                           

  Identificator         5      isgoodday                       isgoodday                       

  Operator              5      :=                              :=                              

scanner_tests\60.in(5) Fatal: Illegal character "Ì"
