 char    type                                                                 0
 double  type                                                                 0
 integer type                                                                 0
 a1      int scalar     20                                                    0
 a2      double scalar  2432.340000                                           0
 a3      double scalar  24.233400                                             0
 a4      int scalar     -20                                                   0
 a5      double scalar  -0.400000                                             0
