 char    type                                                                 0
 double  type                                                                 0
 integer type                                                                 0
 a       int scalar     0                                                     0
 b       int scalar     20                                                    0
 c       int scalar     -2                                                    0
 d       int scalar     820                                                   0
 e       int scalar     5                                                     0
 f       int scalar     20                                                    0
 g       int scalar     2                                                     0
 h       int scalar     6                                                     0
 a1      double scalar  0.500000                                              0
 b1      int scalar     5                                                     0
 c1      double scalar  2.500000                                              0
