 char    type                                                                 0
 double  type                                                                 0
 integer type                                                                 0
 a       int scalar     -50                                                   0
 b       int scalar     34                                                    0
 c       int scalar     0                                                     0
 d       int scalar     1                                                     0
 e       int scalar     0                                                     0
 f       int scalar     1                                                     0
 g       int scalar     0                                                     0
