 char    type                                                                 0
 double  type                                                                 0
 integer type                                                                 0
 tpoint  type alias                      record                               0
 record fields:
 x       variable                        double                               1
 y       variable                        double                               1

 tpoints type alias     array            array[0..100] of tpoint              0
 trec1   type alias                      record                               0
 record fields:
 points1 variable                        tpoints                              1
 points2 variable                        tpoints                              1

