 char    type                                                                 0
 double  type                                                                 0
 integer type                                                                 0
 tt      type alias                      integer                              0
 foo     function                        tt                                   0
 foo params:
 tt1     func param                      char                                 1
 foo locals:
 result  variable                        tt                                   1
 tt      int scalar     25                                                    1

