                               ---- 2                               
                         ---- f2i                         
                   ---- f2i                   
             ---- mod             
                   ---- 5.5                   
       ---- +       
                   ---- b                   
             ---- i2f             
 ---- := 
       ---- a       
program main


